version: "3.8"

services:
  comfyui:
    image: yourname/comfyui:latest
    build: .
    ports:
      - "8188:8188"
    environment:
      - ENABLE_JUPYTER=1
      - ENABLE_TTYD=1
      - COMFYUI_MANAGER_SECURITY=weak
      # - COMFYUI_ARGS=--preview-method auto
      # - COMFYUI_MANAGER_SECURITY_FORCE=1
      # - COMFYUI_AUTO_UPDATE=1
      # - CUSTOM_NODES_AUTO_UPDATE=1
      # - FORCE_CUSTOM_REQUIREMENTS=1
    volumes:
      - ./data:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
